name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Sync
      run: uv sync
    - name: Type Check
      run: uv run pyright
    - name: Lint
      run: uv run ruff check .
    - name: Format Check
      run: uv run black --check custom_components
